[platformio]
default_envs = esp32s3

[env:esp32s3]
platform = espressif32@6.9.0
board = esp32-s3-devkitc-1
framework = arduino
board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_upload.maximum_size = 3145728
board_build.arduino.memory_type = qio_opi
board_build.partitions = app3M_fat9M_16MB.csv
build_flags =
  -DBOARD_HAS_PSRAM
  -DARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
  bblanchon/ArduinoJson@7.3.1
  ESP32Async/AsyncTCP@3.3.2
  ESP32Async/ESPAsyncWebServer@3.6.0
extra_scripts = pre:scripts/embed_web.py
monitor_speed = 115200
